import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer";
import { CartProvider } from "./components/context/CartContext";
import Mybot from "./components/Mybot";





export const metadata: Metadata = {
  title: "Avion Private Limited",
  description: "Generated by Donia Batool",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
        
         
           <CartProvider>{children}</CartProvider>
           <Mybot/>
          <Footer />
        
      </body>
    </html>
  );
}
