import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer";
import Chatbot from "./components/chatbot";



export const metadata: Metadata = {
  title: "Figma into Nextjs",
  description: "Generated by Donia Batool",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <Chatbot/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
